<?php
// Dummy array later with actual db
$foodProducts = [
    [
        'name' => 'Chicken Balls',
        'category' => 'Starter',
        'price' => 1.99,
        'quantity' => 10,
        'image' => 'assets/chicken_ball.jpg',
    ],
    [
        'name' => 'Chicken Katsu',
        'category' => 'Main Dish',
        'price' => 2.49,
        'quantity' => 5,
        'image' => 'assets/chicken_katsu_curry.jpg',
    ],
    [
        'name' => 'Chicken Mega',
        'category' => 'Starter',
        'price' => 1.29,
        'quantity' => 3,
        'image' => 'assets/chicken_mega.jpg',
    ],
    [
        'name' => 'Katsu Deopbap',
        'category' => 'Main Dish',
        'price' => 2.49,
        'quantity' => 5,
        'image' => 'assets/katsu_deopbap.jpg',
    ],
    [
        'name' => 'Katsu Mega',
        'category' => 'Main Dish',
        'price' => 1.29,
        'quantity' => 3,
        'image' => 'assets/katsu_mega.jpg',
    ],
    [
        'name' => 'Mixed Chicken Balls',
        'category' => 'Starter',
        'price' => 1.29,
        'quantity' => 3,
        'image' => 'assets/mixed_chicken_ball.jpg',
    ],
    [
        'name' => 'Prawn Deopbap',
        'category' => 'Main Dish',
        'price' => 1.29,
        'quantity' => 3,
        'image' => 'assets/prawn_deopbap.jpg',
    ],
    [
        'name' => 'Red Tofu',
        'category' => 'Starter',
        'price' => 1.29,
        'quantity' => 3,
        'image' => 'assets/red_tofu.jpg',
    ],
    [
        'name' => 'Tofu Curry',
        'category' => 'Side Dish',
        'price' => 1.29,
        'quantity' => 3,
        'image' => 'assets/tofu_curry.jpg',
    ],
    [
        'name' => 'Tofu Deopbap',
        'category' => 'Main Dish',
        'price' => 1.29,
        'quantity' => 3,
        'image' => 'assets/tofu_deopbap.jpg',
    ],
    [
        'name' => 'Tofu Mega',
        'category' => 'Main Dish',
        'price' => 1.29,
        'quantity' => 3,
        'image' => 'assets/tofu_mega.jpg',
    ],
    [
        'name' => 'Tofu Teriyaki',
        'category' => 'Starter',
        'price' => 1.29,
        'quantity' => 3,
        'image' => 'assets/tofu_teriyaki.jpg',
    ],
];
